[build-system]
requires = [
    "wheel",
    "setuptools",
    "Cython>=0.29.2",
    "oldest-supported-numpy; python_version<'3.9'",
    "numpy>=2; python_version>='3.9'",
]
build-backend = 'setuptools.build_meta'
